name: Build plugin zip

on:
  push:
    tags: ['v*']

permissions:            
  contents: write       # allows updating/releases/uploads

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare folder
        run: |
          mkdir ai-auto-alt-text-generator
          shopt -s extglob
          mv !(ai-auto-alt-text-generator) ai-auto-alt-text-generator/

      - name: Zip plugin
        run: zip -r ai-auto-alt-text-generator.zip ai-auto-alt-text-generator

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ai-auto-alt-text-generator.zip
          draft: false                 # let the action create/publish release
          generate_release_notes: true
